EFFECTS = {
    "STANDARD": {
        "friendly_name": "standard",
        "icon": "mdi:lightbulb",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_VIDEO",
            "isExpert": False,
            "menuSetting": "STANDARD",
        },
    },
    "NATURAL": {
        "friendly_name": "natural",
        "icon": "mdi:leaf",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_VIDEO",
            "isExpert": False,
            "menuSetting": "NATURAL",
        },
    },
    "IMMERSIVE": {
        "friendly_name": "sports",
        "icon": "mdi:soccer",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_VIDEO",
            "isExpert": False,
            "menuSetting": "IMMERSIVE",
        },
    },
    "VIVID": {
        "friendly_name": "vivid",
        "icon": "mdi:palette",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_VIDEO",
            "isExpert": False,
            "menuSetting": "VIVID",
        },
    },
    "GAME": {
        "friendly_name": "game",
        "icon": "mdi:gamepad-variant",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {"styleName": "FOLLOW_VIDEO", "isExpert": False, "menuSetting": "GAME"},
    },
    "COMFORT": {
        "friendly_name": "comfort",
        "icon": "mdi:sofa",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_VIDEO",
            "isExpert": False,
            "menuSetting": "COMFORT",
        },
    },
    "RELAX": {
        "friendly_name": "relax",
        "icon": "mdi:spa",
        "styleName": "FOLLOW_VIDEO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_VIDEO",
            "isExpert": False,
            "menuSetting": "RELAX",
        },
    },
    "VU_METER": {
        "friendly_name": "retro",
        "icon": "mdi:equalizer",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "VU_METER",
        },
    },
    "ENERGY_ADAPTIVE_BRIGHTNESS": {
        "friendly_name": "lumina",
        "icon": "mdi:brightness-5",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "ENERGY_ADAPTIVE_BRIGHTNESS",
        },
    },
    "ENERGY_ADAPTIVE_COLORS": {
        "friendly_name": "colora",
        "icon": "mdi:format-color-fill",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "ENERGY_ADAPTIVE_COLORS",
        },
    },
    "SPECTRUM_ANALYSER": {
        "friendly_name": "spectrum",
        "icon": "mdi:chart-bar",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "SPECTRUM_ANALYSER",
        },
    },
    "KNIGHT_RIDER_CLOCKWISE": {
        "friendly_name": "scanner_clockwise",
        "icon": "mdi:rotate-right",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "KNIGHT_RIDER_CLOCKWISE",
        },
    },
    "KNIGHT_RIDER_ALTERNATING": {
        "friendly_name": "scanner_alternating",
        "icon": "mdi:swap-horizontal",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "KNIGHT_RIDER_ALTERNATING",
        },
    },
    "RANDOM_PIXEL_FLASH": {
        "friendly_name": "rhythm",
        "icon": "mdi:music-note",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "RANDOM_PIXEL_FLASH",
        },
    },
    "MODE_RANDOM": {
        "friendly_name": "random",
        "icon": "mdi:shuffle-variant",
        "styleName": "FOLLOW_AUDIO",
        "endpoint": "ambilight/currentconfiguration",
        "data": {
            "styleName": "FOLLOW_AUDIO",
            "isExpert": False,
            "menuSetting": "MODE_RANDOM",
        },
    },
}
